// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisMaster.WebApps.WebApi.Data;

#nullable disable

namespace SisMaster.WebApps.WebApi.Data.Migrations
{
    [DbContext(typeof(CampeonatoDbContext))]
    [Migration("20261005174120_AdicionarInscricoes")]
    partial class AdicionarInscricoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Associacoes", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<Guid>("AssociacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AssociacaoId");

                    b.ToTable("Campeonatos", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdadeMinima")
                        .HasColumnType("int");

                    b.Property<int>("MinimoPeriodosEmQuadra")
                        .HasColumnType("int");

                    b.Property<int>("MinimoPeriodosForaQuadra")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssociacaoId", "Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFimInscricoes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioInscricoes")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InscricoesHabilitadas")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorBonificacaoPorAtleta")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Temporadas", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.TemporadaCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdadeMinima")
                        .HasColumnType("int");

                    b.Property<int>("MinimoPeriodosEmQuadra")
                        .HasColumnType("int");

                    b.Property<int>("MinimoPeriodosForaQuadra")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TemporadaId", "CategoriaId")
                        .IsUnique();

                    b.ToTable("TemporadaCategorias", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AlturaCm")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConsentimentoLgpdEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomePlanoSaude")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PesoKg")
                        .HasColumnType("int");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Posicao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PossuiPlanoSaude")
                        .HasColumnType("bit");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TemporadaId", "PessoaId");

                    b.ToTable("Inscricoes", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.InscricaoCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<Guid>("InscricaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JustificativaExcecao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RecusadaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TemporadaCategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InscricaoId");

                    b.HasIndex("TemporadaCategoriaId", "Status");

                    b.ToTable("InscricoesCategorias", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Partida.EventoPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("TempoJogoSegundos")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("EventosPartida", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Partida.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CronometroAtivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CronometroIniciadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CronometroSegundosAoIniciar")
                        .HasColumnType("int");

                    b.Property<int>("CronometroSegundosRestantes")
                        .HasColumnType("int");

                    b.Property<int>("FaltasCasa")
                        .HasColumnType("int");

                    b.Property<int>("FaltasVisitante")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoAtual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PlacarCasa")
                        .HasColumnType("int");

                    b.Property<int>("PlacarVisitante")
                        .HasColumnType("int");

                    b.Property<bool>("PosseCasa")
                        .HasColumnType("bit");

                    b.Property<bool>("ShotClockAtivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ShotClockIniciadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShotClockSegundosAoIniciar")
                        .HasColumnType("int");

                    b.Property<int>("ShotClockSegundosRestantes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TimeCasaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TimeVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Time.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Time.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Times", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", "Associacao")
                        .WithMany("Campeonatos")
                        .HasForeignKey("AssociacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associacao");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Categoria", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", "Associacao")
                        .WithMany()
                        .HasForeignKey("AssociacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Associacao");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", "Campeonato")
                        .WithMany("Temporadas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.TemporadaCategoria", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", "Temporada")
                        .WithMany("Categorias")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Inscricao", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Participantes.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", null)
                        .WithMany()
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.InscricaoCategoria", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Participantes.Inscricao", "Inscricao")
                        .WithMany("Categorias")
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.TemporadaCategoria", "TemporadaCategoria")
                        .WithMany()
                        .HasForeignKey("TemporadaCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inscricao");

                    b.Navigation("TemporadaCategoria");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Pessoa", b =>
                {
                    b.OwnsOne("SisMaster.WebApps.WebApi.Domain.Time.VOs.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("PessoaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("PessoaId");

                            b1.HasIndex("Numero")
                                .IsUnique();

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Partida.EventoPartida", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Partida.Partida", "Partida")
                        .WithMany("Eventos")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Time.Jogador", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Time.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SisMaster.WebApps.WebApi.Domain.Time.VOs.Pessoa", "Pessoa", b1 =>
                        {
                            b1.Property<Guid>("JogadorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Nome");

                            b1.HasKey("JogadorId");

                            b1.ToTable("Jogadores");

                            b1.WithOwner()
                                .HasForeignKey("JogadorId");

                            b1.OwnsOne("SisMaster.WebApps.WebApi.Domain.Time.VOs.Cpf", "Cpf", b2 =>
                                {
                                    b2.Property<Guid>("PessoaJogadorId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Numero")
                                        .IsRequired()
                                        .HasMaxLength(11)
                                        .HasColumnType("nvarchar(11)")
                                        .HasColumnName("Cpf");

                                    b2.HasKey("PessoaJogadorId");

                                    b2.HasIndex("Numero")
                                        .IsUnique();

                                    b2.ToTable("Jogadores");

                                    b2.WithOwner()
                                        .HasForeignKey("PessoaJogadorId");
                                });

                            b1.Navigation("Cpf")
                                .IsRequired();
                        });

                    b.Navigation("Pessoa")
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", b =>
                {
                    b.Navigation("Campeonatos");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", b =>
                {
                    b.Navigation("Temporadas");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Inscricao", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Partida.Partida", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Time.Time", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
