// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisMaster.WebApps.WebApi.Data;

#nullable disable

namespace SisMaster.WebApps.WebApi.Data.Migrations
{
    [DbContext(typeof(CampeonatoDbContext))]
    [Migration("20261002190842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Associacoes", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<Guid>("AssociacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AssociacaoId");

                    b.ToTable("Campeonatos", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Partida.EventoPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("TempoJogoSegundos")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("EventosPartida", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Partida.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CronometroAtivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CronometroIniciadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CronometroSegundosAoIniciar")
                        .HasColumnType("int");

                    b.Property<int>("CronometroSegundosRestantes")
                        .HasColumnType("int");

                    b.Property<int>("FaltasCasa")
                        .HasColumnType("int");

                    b.Property<int>("FaltasVisitante")
                        .HasColumnType("int");

                    b.Property<int>("PeriodoAtual")
                        .HasColumnType("int");

                    b.Property<int>("PlacarCasa")
                        .HasColumnType("int");

                    b.Property<int>("PlacarVisitante")
                        .HasColumnType("int");

                    b.Property<bool>("PosseCasa")
                        .HasColumnType("bit");

                    b.Property<bool>("ShotClockAtivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ShotClockIniciadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShotClockSegundosAoIniciar")
                        .HasColumnType("int");

                    b.Property<int>("ShotClockSegundosRestantes")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TimeCasaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TimeVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Time.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Time.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Times", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", "Associacao")
                        .WithMany("Campeonatos")
                        .HasForeignKey("AssociacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associacao");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Partida.EventoPartida", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Partida.Partida", "Partida")
                        .WithMany("Eventos")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Time.Jogador", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Time.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SisMaster.WebApps.WebApi.Domain.Time.VOs.Pessoa", "Pessoa", b1 =>
                        {
                            b1.Property<Guid>("JogadorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Nome");

                            b1.HasKey("JogadorId");

                            b1.ToTable("Jogadores");

                            b1.WithOwner()
                                .HasForeignKey("JogadorId");

                            b1.OwnsOne("SisMaster.WebApps.WebApi.Domain.Time.VOs.Cpf", "Cpf", b2 =>
                                {
                                    b2.Property<Guid>("PessoaJogadorId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Numero")
                                        .IsRequired()
                                        .HasMaxLength(11)
                                        .HasColumnType("nvarchar(11)")
                                        .HasColumnName("Cpf");

                                    b2.HasKey("PessoaJogadorId");

                                    b2.HasIndex("Numero")
                                        .IsUnique();

                                    b2.ToTable("Jogadores");

                                    b2.WithOwner()
                                        .HasForeignKey("PessoaJogadorId");
                                });

                            b1.Navigation("Cpf")
                                .IsRequired();
                        });

                    b.Navigation("Pessoa")
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", b =>
                {
                    b.Navigation("Campeonatos");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Partida.Partida", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Time.Time", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
