// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisMaster.WebApps.WebApi.Data;

#nullable disable

namespace SisMaster.WebApps.WebApi.Data.Migrations
{
    [DbContext(typeof(CampeonatoDbContext))]
    partial class CampeonatoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Associacoes", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AssociacaoId");

                    b.ToTable("Campeonatos", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AceitaAbaixoIdadeMinima")
                        .HasColumnType("bit");

                    b.Property<Guid>("AssociacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdadeMinima")
                        .HasColumnType("int");

                    b.Property<int>("MinimoPeriodosEmQuadra")
                        .HasColumnType("int");

                    b.Property<int>("MinimoPeriodosForaQuadra")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssociacaoId", "Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.DescontoPorCombinacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Combinacao")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId", "Combinacao")
                        .IsUnique();

                    b.ToTable("DescontosPorCombinacao", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CadastroFasesEncerradoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFimInscricoes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioInscricoes")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InscricoesHabilitadas")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TabelaJogosGeradaEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TaxaInscricao")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorBonificacaoPorAtleta")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Temporadas", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.TemporadaCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AceitaAbaixoIdadeMinima")
                        .HasColumnType("bit");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdadeMinima")
                        .HasColumnType("int");

                    b.Property<int>("MinimoPeriodosEmQuadra")
                        .HasColumnType("int");

                    b.Property<int>("MinimoPeriodosForaQuadra")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TemporadaId", "CategoriaId")
                        .IsUnique();

                    b.ToTable("TemporadaCategorias", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Equipes.Atleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InscricaoCategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("InscricaoCategoriaId")
                        .IsUnique();

                    b.ToTable("Atletas", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Equipes.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TemporadaCategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaCategoriaId");

                    b.ToTable("Equipes", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Fases.Fase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ClassificadosPrimeiros")
                        .HasColumnType("int");

                    b.Property<string>("Distribuicao")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DistribuicaoManual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("FaseAnteriorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("JogosPorConfronto")
                        .HasColumnType("int");

                    b.Property<int>("MelhoresExtras")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumeroConfrontos")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroGrupos")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroTurnos")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("TemporadaCategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FaseAnteriorId");

                    b.HasIndex("TemporadaCategoriaId", "Ordem");

                    b.ToTable("Fases", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.Confronto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaseId", "Numero")
                        .IsUnique();

                    b.ToTable("Confrontos", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.FaseEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("FaseId", "Posicao")
                        .IsUnique();

                    b.ToTable("FaseEquipes", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaseId", "Ordem")
                        .IsUnique();

                    b.ToTable("Grupos", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CasaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfrontoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("FaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("Hora")
                        .HasColumnType("time");

                    b.Property<int?>("JogoDaSerie")
                        .HasColumnType("int");

                    b.Property<Guid?>("LocalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Opcional")
                        .HasColumnType("bit");

                    b.Property<int?>("PlacarCasa")
                        .HasColumnType("int");

                    b.Property<int?>("PlacarVisitante")
                        .HasColumnType("int");

                    b.Property<int>("Rodada")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("SumulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CasaId");

                    b.HasIndex("ConfrontoId");

                    b.HasIndex("FaseId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("LocalId");

                    b.HasIndex("VisitanteId");

                    b.HasIndex("TemporadaId", "Numero")
                        .IsUnique();

                    b.ToTable("Jogos", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.Local", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssociacaoId", "Nome", "Cidade")
                        .IsUnique();

                    b.ToTable("Locais", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.SorteioDeDesempate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DefinidoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ordem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FaseId", "GrupoId")
                        .IsUnique()
                        .HasFilter("[GrupoId] IS NOT NULL");

                    b.ToTable("SorteiosDeDesempate", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AlturaCm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CobrancaGeradaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ConsentimentoLgpdEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomePlanoSaude")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PesoKg")
                        .HasColumnType("int");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Posicao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PossuiPlanoSaude")
                        .HasColumnType("bit");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ValorDesconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TemporadaId", "PessoaId");

                    b.ToTable("Inscricoes", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.InscricaoCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InscricaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JustificativaExcecao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RecusadaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TemporadaCategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InscricaoId");

                    b.HasIndex("TemporadaCategoriaId", "Status");

                    b.ToTable("InscricoesCategorias", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.PagamentoInscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("InscricaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InscricaoId");

                    b.ToTable("PagamentosInscricao", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.EventoSumula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SumulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoJogoSegundos")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("SumulaId");

                    b.ToTable("EventosSumula", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChegouNoInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("ChegouNoPeriodo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Titular")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TimeId", "AtletaId")
                        .IsUnique();

                    b.HasIndex("TimeId", "Numero")
                        .IsUnique();

                    b.ToTable("SumulaJogadores", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.Substituicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogadorEntraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JogadorSaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NoInicio")
                        .HasColumnType("bit");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SumulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoJogoSegundos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SumulaId", "Ordem")
                        .IsUnique();

                    b.ToTable("SubstituicoesSumula", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.Sumula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoExterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("CronometroAtivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CronometroIniciadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CronometroSegundosAoIniciar")
                        .HasColumnType("int");

                    b.Property<int>("CronometroSegundosRestantes")
                        .HasColumnType("int");

                    b.Property<int>("FaltasCasa")
                        .HasColumnType("int");

                    b.Property<int>("FaltasVisitante")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ImportadaEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeriodoAtual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PlacarCasa")
                        .HasColumnType("int");

                    b.Property<int>("PlacarVisitante")
                        .HasColumnType("int");

                    b.Property<bool>("PosseCasa")
                        .HasColumnType("bit");

                    b.Property<bool>("ShotClockAtivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ShotClockIniciadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShotClockSegundosAoIniciar")
                        .HasColumnType("int");

                    b.Property<int>("ShotClockSegundosRestantes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TimeCasaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TimeVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoExterno")
                        .IsUnique()
                        .HasFilter("[CodigoExterno] IS NOT NULL");

                    b.HasIndex("JogoId")
                        .IsUnique();

                    b.ToTable("Sumulas", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.SumulaDadosExternos", b =>
                {
                    b.Property<Guid>("SumulaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DadosExternosJson");

                    b.HasKey("SumulaId");

                    b.ToTable("Sumulas", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuxiliarTecnico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CapitaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SumulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tecnico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SumulaId", "Lado")
                        .IsUnique();

                    b.ToTable("SumulaTimes", (string)null);
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", "Associacao")
                        .WithMany("Campeonatos")
                        .HasForeignKey("AssociacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associacao");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Categoria", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", "Associacao")
                        .WithMany()
                        .HasForeignKey("AssociacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Associacao");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.DescontoPorCombinacao", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", null)
                        .WithMany("Descontos")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", "Campeonato")
                        .WithMany("Temporadas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.TemporadaCategoria", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", "Temporada")
                        .WithMany("Categorias")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Equipes.Atleta", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Equipes.Equipe", null)
                        .WithMany("Atletas")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Participantes.InscricaoCategoria", "InscricaoCategoria")
                        .WithMany()
                        .HasForeignKey("InscricaoCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InscricaoCategoria");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Equipes.Equipe", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.TemporadaCategoria", "TemporadaCategoria")
                        .WithMany()
                        .HasForeignKey("TemporadaCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TemporadaCategoria");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Fases.Fase", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Fases.Fase", null)
                        .WithMany()
                        .HasForeignKey("FaseAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.TemporadaCategoria", "TemporadaCategoria")
                        .WithMany()
                        .HasForeignKey("TemporadaCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TemporadaCategoria");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.Confronto", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Fases.Fase", null)
                        .WithMany()
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SisMaster.WebApps.WebApi.Domain.Jogos.ReferenciaEquipe", "OrigemA", b1 =>
                        {
                            b1.Property<Guid>("ConfrontoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ConfrontoOrigemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("EquipeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("FaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("GrupoOrdem")
                                .HasColumnType("int");

                            b1.Property<int?>("Posicao")
                                .HasColumnType("int");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("ConfrontoId");

                            b1.ToTable("Confrontos");

                            b1.WithOwner()
                                .HasForeignKey("ConfrontoId");
                        });

                    b.OwnsOne("SisMaster.WebApps.WebApi.Domain.Jogos.ReferenciaEquipe", "OrigemB", b1 =>
                        {
                            b1.Property<Guid>("ConfrontoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ConfrontoOrigemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("EquipeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("FaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("GrupoOrdem")
                                .HasColumnType("int");

                            b1.Property<int?>("Posicao")
                                .HasColumnType("int");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("ConfrontoId");

                            b1.ToTable("Confrontos");

                            b1.WithOwner()
                                .HasForeignKey("ConfrontoId");
                        });

                    b.Navigation("OrigemA")
                        .IsRequired();

                    b.Navigation("OrigemB")
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.FaseEquipe", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Equipes.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Fases.Fase", null)
                        .WithMany()
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Jogos.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SisMaster.WebApps.WebApi.Domain.Jogos.ReferenciaEquipe", "Origem", b1 =>
                        {
                            b1.Property<Guid>("FaseEquipeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ConfrontoOrigemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("EquipeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("FaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("GrupoOrdem")
                                .HasColumnType("int");

                            b1.Property<int?>("Posicao")
                                .HasColumnType("int");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("FaseEquipeId");

                            b1.ToTable("FaseEquipes");

                            b1.WithOwner()
                                .HasForeignKey("FaseEquipeId");
                        });

                    b.Navigation("Equipe");

                    b.Navigation("Origem")
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.Grupo", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Fases.Fase", null)
                        .WithMany()
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.Jogo", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Jogos.FaseEquipe", "Casa")
                        .WithMany()
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Jogos.Confronto", null)
                        .WithMany()
                        .HasForeignKey("ConfrontoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Fases.Fase", null)
                        .WithMany()
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Jogos.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Jogos.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", null)
                        .WithMany()
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Jogos.FaseEquipe", "Visitante")
                        .WithMany()
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Casa");

                    b.Navigation("Local");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Jogos.Local", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", null)
                        .WithMany()
                        .HasForeignKey("AssociacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Inscricao", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Participantes.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", null)
                        .WithMany()
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.InscricaoCategoria", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Participantes.Inscricao", "Inscricao")
                        .WithMany("Categorias")
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Associacao.TemporadaCategoria", "TemporadaCategoria")
                        .WithMany()
                        .HasForeignKey("TemporadaCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inscricao");

                    b.Navigation("TemporadaCategoria");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.PagamentoInscricao", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Participantes.Inscricao", null)
                        .WithMany("Pagamentos")
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Pessoa", b =>
                {
                    b.OwnsOne("SisMaster.WebApps.WebApi.Domain.Participantes.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("PessoaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("PessoaId");

                            b1.HasIndex("Numero")
                                .IsUnique();

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.EventoSumula", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Sumula.Sumula", "Sumula")
                        .WithMany("Eventos")
                        .HasForeignKey("SumulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sumula");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.Jogador", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Sumula.Time", null)
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.Substituicao", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Sumula.Sumula", null)
                        .WithMany("Substituicoes")
                        .HasForeignKey("SumulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.SumulaDadosExternos", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Sumula.Sumula", null)
                        .WithOne()
                        .HasForeignKey("SisMaster.WebApps.WebApi.Domain.Sumula.SumulaDadosExternos", "SumulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.Time", b =>
                {
                    b.HasOne("SisMaster.WebApps.WebApi.Domain.Sumula.Sumula", null)
                        .WithMany("Times")
                        .HasForeignKey("SumulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Associacao", b =>
                {
                    b.Navigation("Campeonatos");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Campeonato", b =>
                {
                    b.Navigation("Temporadas");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Associacao.Temporada", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Descontos");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Equipes.Equipe", b =>
                {
                    b.Navigation("Atletas");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Participantes.Inscricao", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.Sumula", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Substituicoes");

                    b.Navigation("Times");
                });

            modelBuilder.Entity("SisMaster.WebApps.WebApi.Domain.Sumula.Time", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
